//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StandVirtual.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Anuncio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Anuncio()
        {
            this.Automovel = new HashSet<Automovel>();
            this.Barco = new HashSet<Barco>();
            this.Moto = new HashSet<Moto>();
            this.Peca = new HashSet<Peca>();
        }
    
        public int AnuncioID { get; set; }
        public string Titulo { get; set; }
        public System.DateTime DataCriacao { get; set; }
        public System.DateTime DataExpiracao { get; set; }
        public Nullable<int> NumFav { get; set; }
        public Nullable<int> NumVisualizacoes { get; set; }
        public Nullable<int> NumCliques { get; set; }
        public int Preco { get; set; }
        public string Foto { get; set; }
        public string Video { get; set; }
        public string Descricao { get; set; }
        public int StatusID { get; set; }
        public int UserId { get; set; }
    
        public virtual Status Status { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Automovel> Automovel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Barco> Barco { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Moto> Moto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Peca> Peca { get; set; }
    }
}
