//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StandVirtual.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Automovel
    {
        public string MatriculaAut { get; set; }
        public int Ano { get; set; }
        public int NumPortas { get; set; }
        public string Cor { get; set; }
        public int Potencia { get; set; }
        public int Cilindrada { get; set; }
        public int TipoCaixa { get; set; }
        public double Quilometros { get; set; }
        public int TipoAutomovelID { get; set; }
        public int ModeloID { get; set; }
        public int CombustivelID { get; set; }
        public int AnuncioID { get; set; }
        public bool Importado { get; set; }
    
        public virtual Anuncio Anuncio { get; set; }
        public virtual Combustivel Combustivel { get; set; }
        public virtual Modelo Modelo { get; set; }
        public virtual TipoAutomovel TipoAutomovel { get; set; }
    }
}
