//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StandVirtual.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Barco
    {
        public string MatriculaBarco { get; set; }
        public double HorasNavegacao { get; set; }
        public int Potencia { get; set; }
        public int NumMotores { get; set; }
        public int Comprimento { get; set; }
        public int Lotacao { get; set; }
        public int CapCombustivel { get; set; }
        public int CapAgua { get; set; }
        public int Ano { get; set; }
        public int TipoBarcoID { get; set; }
        public int ModeloID { get; set; }
        public int CombustivelID { get; set; }
        public int AnuncioID { get; set; }
        public bool Importado { get; set; }
    
        public virtual Anuncio Anuncio { get; set; }
        public virtual Combustivel Combustivel { get; set; }
        public virtual Modelo Modelo { get; set; }
        public virtual TipoBarco TipoBarco { get; set; }
    }
}
