//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StandVirtual.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contacto
    {
        public int Contacto1 { get; set; }
        public int NumContacto { get; set; }
        public int TipoContactoID { get; set; }
        public int UserID { get; set; }
    
        public virtual TipoContacto TipoContacto { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
