//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StandVirtual.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StandVirtualTestesEntities1 : DbContext
    {
        public StandVirtualTestesEntities1()
            : base("name=StandVirtualTestesEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Anuncio> Anuncio { get; set; }
        public virtual DbSet<Automovel> Automovel { get; set; }
        public virtual DbSet<Barco> Barco { get; set; }
        public virtual DbSet<Categoria> Categoria { get; set; }
        public virtual DbSet<CodigoPostal> CodigoPostal { get; set; }
        public virtual DbSet<Combustivel> Combustivel { get; set; }
        public virtual DbSet<Contacto> Contacto { get; set; }
        public virtual DbSet<Marca> Marca { get; set; }
        public virtual DbSet<Modelo> Modelo { get; set; }
        public virtual DbSet<Moto> Moto { get; set; }
        public virtual DbSet<Peca> Peca { get; set; }
        public virtual DbSet<Plano> Plano { get; set; }
        public virtual DbSet<Stand> Stand { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<SubCategoria> SubCategoria { get; set; }
        public virtual DbSet<TipoAutomovel> TipoAutomovel { get; set; }
        public virtual DbSet<TipoBarco> TipoBarco { get; set; }
        public virtual DbSet<TipoCombustivel> TipoCombustivel { get; set; }
        public virtual DbSet<TipoContacto> TipoContacto { get; set; }
        public virtual DbSet<TipoMota> TipoMota { get; set; }
        public virtual DbSet<TipoPeca> TipoPeca { get; set; }
        public virtual DbSet<TipoPerm> TipoPerm { get; set; }
        public virtual DbSet<TipoPlano> TipoPlano { get; set; }
        public virtual DbSet<TipoStatus> TipoStatus { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    }
}
