//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StandVirtual.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Peca
    {
        public int PecaID { get; set; }
        public string Nome { get; set; }
        public string Fabricante { get; set; }
        public string Referencia { get; set; }
        public int TipoPecaID { get; set; }
        public int CategoriaID { get; set; }
        public int ModeloID { get; set; }
        public int AnuncioID { get; set; }
    
        public virtual Anuncio Anuncio { get; set; }
        public virtual Categoria Categoria { get; set; }
        public virtual Modelo Modelo { get; set; }
        public virtual TipoPeca TipoPeca { get; set; }
    }
}
