//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StandVirtual.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plano
    {
        public int PlanoID { get; set; }
        public int Custo { get; set; }
        public int TipoPlanoID { get; set; }
        public int UserID { get; set; }
    
        public virtual TipoPlano TipoPlano { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
