//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StandVirtual.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubCategoria
    {
        public int SubCatID { get; set; }
        public string NomeSubCat { get; set; }
        public int CategoriaID { get; set; }
    
        public virtual Categoria Categoria { get; set; }
    }
}
